[package]
name = "lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[lib]
name="riscv_csr_macros"
path="src/riscv_csr_macros.rs"

[[example]]
name="test_csr"
path="examples/test_csr.rs"
